import type { ContractTemplate, ContractField, ContractClause } from './types';

const landlordFields: ContractField[] = [
  {
    id: 'landlord.name',
    label: 'نام و نام خانوادگی موجر',
    type: 'text',
    required: true,
    placeholder: 'علی رضایی',
    group: 'landlord',
    groupLabel: 'اطلاعات موجر (مالک)',
  },
  {
    id: 'landlord.nationalId',
    label: 'کد ملی موجر',
    type: 'text',
    required: true,
    placeholder: '0012345678',
    group: 'landlord',
    groupLabel: 'اطلاعات موجر (مالک)',
  },
  {
    id: 'landlord.phone',
    label: 'شماره تلفن موجر',
    type: 'text',
    required: true,
    placeholder: '09121234567',
    group: 'landlord',
    groupLabel: 'اطلاعات موجر (مالک)',
  },
  {
    id: 'landlord.address',
    label: 'آدرس موجر',
    type: 'text',
    required: true,
    placeholder: 'تهران، خیابان ولیعصر، کوچه ۱۰',
    group: 'landlord',
    groupLabel: 'اطلاعات موجر (مالک)',
  },
];

const tenantFields: ContractField[] = [
  {
    id: 'tenant.name',
    label: 'نام و نام خانوادگی مستأجر',
    type: 'text',
    required: true,
    placeholder: 'محمد محمدی',
    group: 'tenant',
    groupLabel: 'اطلاعات مستأجر',
  },
  {
    id: 'tenant.nationalId',
    label: 'کد ملی مستأجر',
    type: 'text',
    required: true,
    placeholder: '0098765432',
    group: 'tenant',
    groupLabel: 'اطلاعات مستأجر',
  },
  {
    id: 'tenant.phone',
    label: 'شماره تلفن مستأجر',
    type: 'text',
    required: true,
    placeholder: '09351234567',
    group: 'tenant',
    groupLabel: 'اطلاعات مستأجر',
  },
  {
    id: 'tenant.address',
    label: 'آدرس مستأجر',
    type: 'text',
    required: true,
    placeholder: 'تهران، خیابان آزادی',
    group: 'tenant',
    groupLabel: 'اطلاعات مستأجر',
  },
];

const propertyFields: ContractField[] = [
  {
    id: 'property.address',
    label: 'آدرس ملک مورد اجاره',
    type: 'text',
    required: true,
    placeholder: 'تهران، خیابان ...',
    group: 'property',
    groupLabel: 'اطلاعات ملک',
  },
  {
    id: 'property.postalCode',
    label: 'کد پستی ملک',
    type: 'text',
    required: true,
    placeholder: '1234567890',
    group: 'property',
    groupLabel: 'اطلاعات ملک',
  },
  {
    id: 'property.area',
    label: 'متراژ (متر مربع)',
    type: 'text',
    required: true,
    placeholder: '85',
    group: 'property',
    groupLabel: 'اطلاعات ملک',
  },
  {
    id: 'property.floor',
    label: 'طبقه',
    type: 'text',
    required: false,
    placeholder: '3',
    group: 'property',
    groupLabel: 'اطلاعات ملک',
  },
  {
    id: 'property.unit',
    label: 'واحد',
    type: 'text',
    required: false,
    placeholder: '2',
    group: 'property',
    groupLabel: 'اطلاعات ملک',
  },
  {
    id: 'property.deedType',
    label: 'نوع سند',
    type: 'select',
    required: true,
    options: ['قولنامه‌ای', 'ششدانگ', 'تک‌دانگ', 'سایر'],
    group: 'property',
    groupLabel: 'اطلاعات ملک',
  },
  {
    id: 'property.utilities',
    label: 'وضعیت انشعابات',
    type: 'textarea',
    required: false,
    placeholder: 'برق، گاز، آب، تلفن، اینترنت',
    group: 'property',
    groupLabel: 'اطلاعات ملک',
  },
  {
    id: 'property.fixtures',
    label: 'لوازم و تجهیزات',
    type: 'textarea',
    required: false,
    placeholder: 'یخچال، اجاق‌گاز، کولر، لباسشویی',
    group: 'property',
    groupLabel: 'اطلاعات ملک',
  },
];

const termFields: ContractField[] = [
  {
    id: 'startDate',
    label: 'تاریخ شروع اجاره',
    type: 'date',
    required: true,
    group: 'term',
    groupLabel: 'مدت و تاریخ‌ها',
  },
  {
    id: 'endDate',
    label: 'تاریخ پایان اجاره',
    type: 'date',
    required: true,
    group: 'term',
    groupLabel: 'مدت و تاریخ‌ها',
  },
  {
    id: 'deliveryDate',
    label: 'تاریخ تحویل ملک',
    type: 'date',
    required: true,
    group: 'term',
    groupLabel: 'مدت و تاریخ‌ها',
  },
];

const financialFields: ContractField[] = [
  {
    id: 'depositAmount',
    label: 'مبلغ ودیعه (تومان)',
    type: 'text',
    required: true,
    placeholder: '500,000,000',
    group: 'financials',
    groupLabel: 'مبالغ و پرداخت',
  },
  {
    id: 'monthlyRent',
    label: 'مبلغ اجاره ماهانه (تومان)',
    type: 'text',
    required: true,
    placeholder: '15,000,000',
    group: 'financials',
    groupLabel: 'مبالغ و پرداخت',
  },
  {
    id: 'paymentDay',
    label: 'روز پرداخت اجاره',
    type: 'text',
    required: true,
    placeholder: 'اول هر ماه',
    group: 'financials',
    groupLabel: 'مبالغ و پرداخت',
  },
  {
    id: 'paymentMethod',
    label: 'روش پرداخت',
    type: 'select',
    required: true,
    options: ['انتقال بانکی', 'چک', 'نقد', 'واریز به حساب'],
    group: 'financials',
    groupLabel: 'مبالغ و پرداخت',
  },
];

const obligationFields: ContractField[] = [
  {
    id: 'utilityCosts',
    label: 'هزینه انشعابات',
    type: 'textarea',
    required: false,
    placeholder: 'پرداخت قبوض بر عهده مستأجر است',
    group: 'obligations',
    groupLabel: 'تعهدات و شرایط',
  },
  {
    id: 'municipalCharges',
    label: 'عوارض شهرداری',
    type: 'textarea',
    required: false,
    placeholder: 'عوارض شهرداری بر عهده موجر/مستأجر',
    group: 'obligations',
    groupLabel: 'تعهدات و شرایط',
  },
  {
    id: 'taxFees',
    label: 'مالیات و عوارض',
    type: 'textarea',
    required: false,
    placeholder: 'مالیات بر اجاره بر عهده مستأجر',
    group: 'obligations',
    groupLabel: 'تعهدات و شرایط',
  },
  {
    id: 'subleasePermission',
    label: 'اجازه اجاره مجدد',
    type: 'select',
    required: false,
    options: ['با اجازه موجر', 'بدون اجازه'],
    group: 'obligations',
    groupLabel: 'تعهدات و شرایط',
  },
  {
    id: 'latePaymentPenalty',
    label: 'جریمه تأخیر در پرداخت',
    type: 'textarea',
    required: false,
    placeholder: 'در صورت تأخیر بیش از ۱۰ روز، روزانه X تومان',
    group: 'obligations',
    groupLabel: 'تعهدات و شرایط',
  },
  {
    id: 'lateVacatePenalty',
    label: 'جریمه تأخیر در تخلیه',
    type: 'textarea',
    required: false,
    placeholder: 'روزانه Y تومان',
    group: 'obligations',
    groupLabel: 'تعهدات و شرایط',
  },
];

const witnessFields: ContractField[] = [
  {
    id: 'witness1',
    label: 'نام شاهد اول',
    type: 'text',
    required: false,
    placeholder: 'شاهد اول',
    group: 'witnesses',
    groupLabel: 'شاهدان',
  },
  {
    id: 'witness2',
    label: 'نام شاهد دوم',
    type: 'text',
    required: false,
    placeholder: 'شاهد دوم',
    group: 'witnesses',
    groupLabel: 'شاهدان',
  },
];

const rentalClauses: ContractClause[] = [
  {
    id: 'default-obligations',
    title: 'تعهدات مستأجر',
    text: 'مستأجر متعهد است اجاره‌بها را در موعد مقرر پرداخت نماید و از اجاره دادن ملک به غیر بدون اجازه کتبی موجر خودداری کند.',
    required: true,
    defaultEnabled: true,
  },
  {
    id: 'default-maintenance',
    title: 'تعمیرات و نگهداری',
    text: 'تعمیرات جزئی بر عهده مستأجر و تعمیرات اساسی (سقف، لوله‌کشی، تأسیسات) بر عهده موجر است.',
    required: true,
    defaultEnabled: true,
  },
  {
    id: 'default-inspection',
    title: 'بازدید ملک',
    text: 'موجر حق بازدید ملک را با هماهنگی قبلی و در ساعات منطقی دارد.',
    required: false,
    defaultEnabled: true,
  },
  {
    id: 'default-termination',
    title: 'فسخ قرارداد',
    text: 'هر یک از طرفین با اطلاع‌رسانی کتبی ۳ ماهه می‌تواند قرارداد را فسخ کند.',
    required: false,
    defaultEnabled: false,
  },
];

const rentalOptionalClauses: ContractClause[] = [
  {
    id: 'optional-parking',
    title: 'پارکینگ',
    text: 'یک پارکینگ سرپوشیده به شماره ... در اختیار مستأجر قرار می‌گیرد.',
    required: false,
    defaultEnabled: false,
  },
  {
    id: 'optional-storage',
    title: 'انباری',
    text: 'یک انباری به متراژ ... در اختیار مستأجر قرار می‌گیرد.',
    required: false,
    defaultEnabled: false,
  },
  {
    id: 'optional-pet',
    title: 'نگهداری حیوان خانگی',
    text: 'نگهداری حیوان خانگی با رضایت کتبی موجر بلامانع است.',
    required: false,
    defaultEnabled: false,
  },
  {
    id: 'optional-guarantor',
    title: 'ضامن',
    text: 'نام ضامن: ... کد ملی: ...',
    required: false,
    defaultEnabled: false,
  },
];

export const rentalLeaseTemplate: ContractTemplate = {
  templateId: 'rental-lease',
  version: '1.0.0',
  title: 'قرارداد اجاره مسکونی',
  description: 'پیش‌نویس قرارداد اجاره مسکونی با اطلاعات کامل طرفین، ملک، مبلغ و شرایط',
  fields: [
    ...landlordFields,
    ...tenantFields,
    ...propertyFields,
    ...termFields,
    ...financialFields,
    ...obligationFields,
    ...witnessFields,
  ],
  requiredFields: [
    'landlord.name',
    'landlord.nationalId',
    'landlord.phone',
    'landlord.address',
    'tenant.name',
    'tenant.nationalId',
    'tenant.phone',
    'tenant.address',
    'property.address',
    'property.postalCode',
    'property.area',
    'property.deedType',
    'startDate',
    'endDate',
    'deliveryDate',
    'depositAmount',
    'monthlyRent',
    'paymentDay',
    'paymentMethod',
  ],
  clauses: rentalClauses,
  optionalClauses: rentalOptionalClauses,
  disclaimers: [],
  pricingTier: 'free',
  lastReviewedAt: '2026-06-26',
  reviewStatus: 'needs-legal-review',
};

const constructionClientFields: ContractField[] = [
  {
    id: 'client.name',
    label: 'نام کارفرما',
    type: 'text',
    required: true,
    placeholder: 'نام کارفرما',
    group: 'client',
    groupLabel: 'اطلاعات کارفرما',
  },
  {
    id: 'client.nationalId',
    label: 'کد ملی / شماره ثبت کارفرما',
    type: 'text',
    required: true,
    placeholder: '0012345678',
    group: 'client',
    groupLabel: 'اطلاعات کارفرما',
  },
  {
    id: 'client.phone',
    label: 'شماره تلفن کارفرما',
    type: 'text',
    required: true,
    placeholder: '09121234567',
    group: 'client',
    groupLabel: 'اطلاعات کارفرما',
  },
  {
    id: 'client.address',
    label: 'آدرس کارفرما',
    type: 'text',
    required: true,
    group: 'client',
    groupLabel: 'اطلاعات کارفرما',
  },
  {
    id: 'client.registrationNo',
    label: 'شماره ثبت (اختیاری)',
    type: 'text',
    required: false,
    group: 'client',
    groupLabel: 'اطلاعات کارفرما',
  },
];

const constructionContractorFields: ContractField[] = [
  {
    id: 'contractor.name',
    label: 'نام پیمانکار / معمار',
    type: 'text',
    required: true,
    group: 'contractor',
    groupLabel: 'اطلاعات پیمانکار / معمار',
  },
  {
    id: 'contractor.nationalId',
    label: 'کد ملی / شماره ثبت پیمانکار',
    type: 'text',
    required: true,
    group: 'contractor',
    groupLabel: 'اطلاعات پیمانکار / معمار',
  },
  {
    id: 'contractor.phone',
    label: 'شماره تلفن پیمانکار',
    type: 'text',
    required: true,
    group: 'contractor',
    groupLabel: 'اطلاعات پیمانکار / معمار',
  },
  {
    id: 'contractor.address',
    label: 'آدرس پیمانکار',
    type: 'text',
    required: true,
    group: 'contractor',
    groupLabel: 'اطلاعات پیمانکار / معمار',
  },
  {
    id: 'contractor.registrationNo',
    label: 'شماره ثبت (اختیاری)',
    type: 'text',
    required: false,
    group: 'contractor',
    groupLabel: 'اطلاعات پیمانکار / معمار',
  },
];

const constructionProjectFields: ContractField[] = [
  {
    id: 'projectTitle',
    label: 'عنوان پروژه',
    type: 'text',
    required: true,
    placeholder: 'ساخت ویلای مسکونی',
    group: 'project',
    groupLabel: 'اطلاعات پروژه',
  },
  {
    id: 'projectAddress',
    label: 'آدرس پروژه',
    type: 'text',
    required: true,
    group: 'project',
    groupLabel: 'اطلاعات پروژه',
  },
  {
    id: 'scopeOfWork',
    label: 'شرح خدمات / موضوع قرارداد',
    type: 'textarea',
    required: true,
    placeholder: 'طراحی و نظارت بر اجرای ساختمان مسکونی',
    group: 'project',
    groupLabel: 'اطلاعات پروژه',
  },
  {
    id: 'deliverables',
    label: 'تحویل‌ها / خروجی‌ها',
    type: 'textarea',
    required: true,
    placeholder: 'نقشه‌های اجرایی، لیست مصالح، نظارت بر اجرا',
    group: 'project',
    groupLabel: 'اطلاعات پروژه',
  },
  {
    id: 'milestones',
    label: 'مراحل کار',
    type: 'textarea',
    required: false,
    placeholder: 'مرحله ۱: طراحی / مرحله ۲: نظارت',
    group: 'project',
    groupLabel: 'اطلاعات پروژه',
  },
];

const constructionDateFields: ContractField[] = [
  {
    id: 'startDate',
    label: 'تاریخ شروع',
    type: 'date',
    required: true,
    group: 'dates',
    groupLabel: 'تاریخ‌ها',
  },
  {
    id: 'endDate',
    label: 'تاریخ پایان',
    type: 'date',
    required: true,
    group: 'dates',
    groupLabel: 'تاریخ‌ها',
  },
];

const constructionFinancialFields: ContractField[] = [
  {
    id: 'contractAmount',
    label: 'مبلغ قرارداد (تومان)',
    type: 'text',
    required: true,
    placeholder: '500,000,000',
    group: 'construction_financials',
    groupLabel: 'مبالغ و پرداخت',
  },
  {
    id: 'paymentStructure',
    label: 'ساختار پرداخت',
    type: 'textarea',
    required: true,
    placeholder: '۳۰٪ پیش‌پرداخت + ۴۰٪ حین کار + ۳۰٪ تحویل نهایی',
    group: 'construction_financials',
    groupLabel: 'مبالغ و پرداخت',
  },
  {
    id: 'advancePayment',
    label: 'پیش‌پرداخت (تومان)',
    type: 'text',
    required: false,
    group: 'construction_financials',
    groupLabel: 'مبالغ و پرداخت',
  },
];

const constructionObligationFields: ContractField[] = [
  {
    id: 'delayPenalty',
    label: 'جریمه تأخیر',
    type: 'textarea',
    required: false,
    placeholder: 'روزانه ۰.۱٪ مبلغ قرارداد',
    group: 'construction_obligations',
    groupLabel: 'تعهدات و شرایط',
  },
  {
    id: 'changeOrderRule',
    label: 'تغییرات و الحاقیه',
    type: 'textarea',
    required: false,
    placeholder: 'تغییرات فقط با توافق کتبی طرفین',
    group: 'construction_obligations',
    groupLabel: 'تعهدات و شرایط',
  },
  {
    id: 'confidentiality',
    label: 'بند محرمانگی',
    type: 'textarea',
    required: false,
    group: 'construction_obligations',
    groupLabel: 'تعهدات و شرایط',
  },
  {
    id: 'ipOwnership',
    label: 'مالکیت نقشه‌ها و طرح‌ها',
    type: 'textarea',
    required: false,
    group: 'construction_obligations',
    groupLabel: 'تعهدات و شرایط',
  },
  {
    id: 'permitResponsibility',
    label: 'مسئولیت مجوزها',
    type: 'textarea',
    required: false,
    group: 'construction_obligations',
    groupLabel: 'تعهدات و شرایط',
  },
  {
    id: 'insurance',
    label: 'بیمه و مسئولیت',
    type: 'textarea',
    required: false,
    group: 'construction_obligations',
    groupLabel: 'تعهدات و شرایط',
  },
  {
    id: 'handoverConditions',
    label: 'شرایط تحویل نهایی',
    type: 'textarea',
    required: false,
    group: 'construction_obligations',
    groupLabel: 'تعهدات و شرایط',
  },
  {
    id: 'terminationConditions',
    label: 'شرایط فسخ',
    type: 'textarea',
    required: false,
    group: 'construction_obligations',
    groupLabel: 'تعهدات و شرایط',
  },
  {
    id: 'disputeResolution',
    label: 'حل اختلاف',
    type: 'textarea',
    required: false,
    placeholder: 'داوری / دادگاه صالح',
    group: 'construction_obligations',
    groupLabel: 'تعهدات و شرایط',
  },
];

const constructionWitnessFields: ContractField[] = [
  {
    id: 'witness1',
    label: 'نام شاهد اول',
    type: 'text',
    required: false,
    group: 'construction_witnesses',
    groupLabel: 'شاهدان',
  },
  {
    id: 'witness2',
    label: 'نام شاهد دوم',
    type: 'text',
    required: false,
    group: 'construction_witnesses',
    groupLabel: 'شاهدان',
  },
];

const constructionClauses: ContractClause[] = [
  {
    id: 'construction-scope',
    title: 'موضوع قرارداد',
    text: 'موضوع این قرارداد اجرای خدمات موضوع قرارداد طبق شرح خدمات مندرج در قرارداد است.',
    required: true,
    defaultEnabled: true,
  },
  {
    id: 'construction-obligations',
    title: 'تعهدات پیمانکار',
    text: 'پیمانکار متعهد است خدمات موضوع قرارداد را طبق استانداردهای فنی و در موعد مقرر انجام دهد.',
    required: true,
    defaultEnabled: true,
  },
  {
    id: 'construction-payment',
    title: 'نحوه پرداخت',
    text: 'پرداخت‌ها طبق جدول زمانی و شرایط مندرج در قرارداد انجام می‌شود.',
    required: true,
    defaultEnabled: true,
  },
];

const constructionOptionalClauses: ContractClause[] = [
  {
    id: 'construction-warranty',
    title: 'گارانتی',
    text: 'پیمانکار گارانتی ... ماهه برای خدمات ارائه‌شده ارائه می‌دهد.',
    required: false,
    defaultEnabled: false,
  },
  {
    id: 'construction-force-majeure',
    title: 'فورس ماژور',
    text: 'در صورت بروز حوادث غیرمترقبه، مهلت اجرا به اندازه مدت تأخیر تمدید می‌شود.',
    required: false,
    defaultEnabled: true,
  },
];

export const constructionContractorTemplate: ContractTemplate = {
  templateId: 'construction-contractor',
  version: '1.0.0',
  title: 'قرارداد پیمانکاری / معماری ساختمان',
  description: 'پیش‌نویس قرارداد پیمانکاری و معماری ساختمان با اطلاعات کامل طرفین، پروژه و شرایط',
  fields: [
    ...constructionClientFields,
    ...constructionContractorFields,
    ...constructionProjectFields,
    ...constructionDateFields,
    ...constructionFinancialFields,
    ...constructionObligationFields,
    ...constructionWitnessFields,
  ],
  requiredFields: [
    'client.name',
    'client.nationalId',
    'client.phone',
    'client.address',
    'contractor.name',
    'contractor.nationalId',
    'contractor.phone',
    'contractor.address',
    'projectTitle',
    'projectAddress',
    'scopeOfWork',
    'deliverables',
    'startDate',
    'endDate',
    'contractAmount',
    'paymentStructure',
  ],
  clauses: constructionClauses,
  optionalClauses: constructionOptionalClauses,
  disclaimers: [],
  pricingTier: 'free',
  lastReviewedAt: '2026-06-26',
  reviewStatus: 'needs-legal-review',
};

export const allTemplates: Record<string, ContractTemplate> = {
  'rental-lease': rentalLeaseTemplate,
  'construction-contractor': constructionContractorTemplate,
};

export function getTemplate(templateId: string): ContractTemplate | undefined {
  return allTemplates[templateId];
}

export function getAllTemplates(): ContractTemplate[] {
  return Object.values(allTemplates);
}
